model_params:
  name: 'VanillaVAE'
  in_channels: 784
  latent_dim: 20
  hidden_dims: [400]

exp_params:
  dataset: mnist
  data_path: "/content/MNIST"
  img_size: 28
  batch_size: 100 # Better to have a square number
  LR: 0.005
  weight_decay: 0.0
  scheduler_gamma: 0.95

trainer_params:
  gpus: 1
  max_nb_epochs: 10
  max_epochs: 10

logging_params:
  save_dir: "/content/logs/"
  name: "VanillaVAE"
  manual_seed: 1265
